# Generated by Django 4.0 on 2022-01-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название возрастного рейтинга')),
                ('description', models.TextField(verbose_name='Описание возрастного рейтинга')),
            ],
            options={
                'verbose_name': 'Возрастной рейтинг',
                'verbose_name_plural': 'Возрастные рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=255, verbose_name='Русское название')),
                ('name_jap', models.CharField(default='', max_length=255, verbose_name='Японское название')),
                ('poster', models.ImageField(default='', upload_to='', verbose_name='Постер')),
                ('status', models.CharField(choices=[('AN', 'Анонсировано'), ('ON', 'Онгоинг'), ('RE', 'Вышедшее')], default='AN', max_length=2, verbose_name='Статус выхода')),
                ('type', models.CharField(choices=[('TV', 'TV Сериал'), ('FM', 'Фильм'), ('OV', 'OVA'), ('ON', 'ONA'), ('SP', 'Спешл')], default='TV', max_length=2, verbose_name='Тип аниме')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Описание аниме')),
                ('number_of_episodes', models.PositiveSmallIntegerField(default=0, verbose_name='Количество эпизодов')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя персонажа')),
                ('description', models.TextField(verbose_name='Описание персонажа')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название франшизы')),
            ],
            options={
                'verbose_name': 'Франшиза',
                'verbose_name_plural': 'Франшизы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название жанра')),
                ('description', models.TextField(verbose_name='Описание жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='CartAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка пользователя')),
                ('number_of_episodes_watched', models.PositiveSmallIntegerField(default=0, verbose_name='Количество просмотренных эпизодов')),
                ('view_status', models.CharField(choices=[('PL', 'Запланировано'), ('WA', 'Смотрю'), ('VI', 'Просмотрено'), ('RE', 'Пересматриваю'), ('AB', 'Брошено'), ('PO', 'Отложено')], default='PL', max_length=2, verbose_name='Статус просмотра')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anime', verbose_name='Аниме')),
            ],
        ),
    ]
