# Generated by Django 4.0 on 2022-01-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartanime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='anime',
            name='age_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agerating', verbose_name='Возрастной статус'),
        ),
        migrations.AddField(
            model_name='anime',
            name='characters',
            field=models.ManyToManyField(related_name='anime', to='api.Character', verbose_name='Персонажи'),
        ),
        migrations.AddField(
            model_name='anime',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.franchise', verbose_name='Франшиза'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='anime', to='api.Genre', verbose_name='Жанры'),
        ),
    ]
