# Generated by Django 4.0 on 2022-01-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agerating',
            options={'verbose_name': 'Возрастной рейтинг', 'verbose_name_plural': 'Возрастные рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Аниме', 'verbose_name_plural': 'Аниме'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='franchise',
            options={'verbose_name': 'Франшиза', 'verbose_name_plural': 'Франшизы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='starrating',
            options={'verbose_name': 'Оценочный рейтинг', 'verbose_name_plural': 'Оценочные рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус выхода', 'verbose_name_plural': 'Статусы выхода'},
        ),
        migrations.RemoveField(
            model_name='anime',
            name='name_eng',
        ),
        migrations.AddField(
            model_name='anime',
            name='name_jap',
            field=models.CharField(default='', max_length=255, verbose_name='Японское название'),
        ),
    ]
