# Generated by Django 4.0 on 2022-01-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartanime',
            options={'verbose_name': 'Аниме для списка', 'verbose_name_plural': 'Аниме для списка'},
        ),
    ]
