# Generated by Django 4.0 on 2022-01-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_alter_agerating_options_alter_anime_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка пользователя')),
                ('number_of_episodes_watched', models.PositiveSmallIntegerField(default=0, verbose_name='Количество просмотренных эпизодов')),
                ('view_status', models.CharField(choices=[('PL', 'Запланировано'), ('WA', 'Смотрю'), ('VI', 'Просмотрено'), ('RE', 'Пересматриваю'), ('AB', 'Брошено'), ('PO', 'Отложено')], default='PL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=63, verbose_name='Никнейм пользователя')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Аватар пользователя')),
                ('about', models.TextField(verbose_name='"О себе" пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='number_of_episodes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество эпизодов'),
        ),
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.ImageField(default='', upload_to='', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('AN', 'Анонсировано'), ('ON', 'Онгоинг'), ('RE', 'Вышедшее')], default='AN', max_length=2),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='cartanime',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anime', verbose_name='Аниме'),
        ),
        migrations.AddField(
            model_name='cartanime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
        ),
    ]
