# Generated by Django 4.0 on 2022-01-07 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_about_alter_user_avatar_and_more'),
        ('api', '0003_alter_cartanime_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartanime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='users.user', verbose_name='Пользователь'),
        ),
    ]
