# Generated by Django 4.0 on 2022-01-08 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_about_alter_user_avatar_and_more'),
        ('api', '0004_alter_cartanime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartanime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_anime', to='users.user', verbose_name='Пользователь'),
        ),
    ]
