# Generated by Django 4.0 on 2022-01-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_starrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('TV', 'TV Сериал'), ('FM', 'Фильм'), ('OV', 'OVA'), ('ON', 'ONA'), ('SP', 'Спешл')], default='TV', max_length=2, verbose_name='Тип аниме'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('AN', 'Анонсировано'), ('ON', 'Онгоинг'), ('RE', 'Вышедшее')], default='AN', max_length=2, verbose_name='Статус выхода'),
        ),
    ]
