# Generated by Django 4.0 on 2022-01-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cartanime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartanime',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_anime', to='api.anime', verbose_name='Аниме'),
        ),
    ]
